name: example
description: ffmpeg.wasm for Flutter web example.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.0.5
  ffmpeg_wasm:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true