name: ffmpeg_wasm
description: ffmpeg.wasm browser APIs dart port for accessing in Flutter web.
version: 1.0.1
homepage: "https://github.com/redleafsofts/flutter_ffmpeg_wasm"
repository: "https://github.com/redleafsofts/flutter_ffmpeg_wasm"

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


#flutter:
#  plugin:
#    platforms:
#      web:
#        pluginClass: FFmpeg
#        fileName: src/ffmpeg.dart